version: "3.3"

networks:
  ping-net:

services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - ping-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  studentappfrontend:
    image: bansikah/studentappfrontend:v1.1
    networks:
      - ping-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    restart: unless-stopped

  studentappbackend:
    image: bansikah/studentapp:v1.1
    environment:
      - APP_VERSION=0.0.1-SNAPSHOT
    networks:
      - ping-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8081"
    restart: unless-stopped