name: Build & Deploy frontend

on:
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World script
        run: echo "Hello World"