name: Build & Deploy Release

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        run: cd studentapp && npm install --force && npm run build  # Assuming build script in frontend

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}  # Use commit SHA for tag (replace with versioning if needed)
          release_name: "Release from ${{ github.sha }}"  # Use commit SHA for release name (replace with versioning if needed)
          body: "This release corresponds to commit ${{ github.sha }}"  # Optional release description
